import 'dart:io';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:screenshot/screenshot.dart';
import 'package:flutter/services.dart';

class SharingService {
  static final ScreenshotController screenshotController = ScreenshotController();

  static Future<void> shareAsPlainText(String text) async {
    await Share.share(text);
  }

  static Future<void> copyToClipboard(BuildContext context, String text) async {
    await Clipboard.setData(ClipboardData(text: text));
    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Copied to clipboard')),
      );
    }
  }

  static Future<void> shareAsPdf(String title, String content) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text(content, style: const pw.TextStyle(fontSize: 12)),
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.Footer(
                trailing: pw.Text('Generated by SilentScribe', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
              ),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/SilentScribe_Report.pdf");
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles([XFile(file.path)], text: 'Check out this transcription from SilentScribe');
  }

  static Future<void> shareAsImage(BuildContext context, String content, String style) async {
    // Show a dialog with the preview and then capture it
    // Or capture a hidden widget
    
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    final imageWidget = Container(
      padding: const EdgeInsets.all(40),
      width: 1080,
      height: 1080,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: isDark 
            ? [const Color(0xFF1A1A2E), const Color(0xFF16213E)]
            : [const Color(0xFFF8F9FA), const Color(0xFFE9ECEF)],
        ),
      ),
      child: Center(
        child: Container(
          padding: const EdgeInsets.all(40),
          decoration: BoxDecoration(
            color: isDark ? Colors.white.withOpacity(0.05) : Colors.black.withOpacity(0.02),
            borderRadius: BorderRadius.circular(32),
            border: Border.all(color: isDark ? Colors.white.withOpacity(0.1) : Colors.black.withOpacity(0.05)),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.format_quote_rounded, size: 80, color: theme.colorScheme.primary.withOpacity(0.5)),
              const SizedBox(height: 24),
              Text(
                content,
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 32,
                  fontFamily: 'Inter',
                  fontWeight: FontWeight.w500,
                  color: isDark ? Colors.white : Colors.black87,
                  height: 1.4,
                ),
                maxLines: 12,
                overflow: TextOverflow.ellipsis,
              ),
              const SizedBox(height: 40),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    width: 40,
                    height: 2,
                    color: theme.colorScheme.primary,
                  ),
                  const SizedBox(width: 16),
                  Text(
                    style.toUpperCase(),
                    style: TextStyle(
                      letterSpacing: 2,
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: theme.colorScheme.primary,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Container(
                    width: 40,
                    height: 2,
                    color: theme.colorScheme.primary,
                  ),
                ],
              ),
              const SizedBox(height: 40),
              Text(
                'Generated with SilentScribe',
                style: TextStyle(
                  fontSize: 16,
                  color: (isDark ? Colors.white : Colors.black).withOpacity(0.4),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    final Uint8List? imageBytes = await screenshotController.captureFromWidget(
      imageWidget,
      context: context,
      delay: const Duration(milliseconds: 100),
    );

    if (imageBytes != null) {
      final directory = await getTemporaryDirectory();
      final imagePath = '${directory.path}/SilentScribe_Quote.png';
      final imageFile = File(imagePath);
      await imageFile.writeAsBytes(imageBytes);

      await Share.shareXFiles([XFile(imagePath)], text: 'Check out this transcription from SilentScribe');
    }
  }
}
